name: Deploy App to GCP VM

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to GCP VM via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.GCP_USER }}/toc-resume-parser"

    - name: SSH into GCP VM and deploy with Docker
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd ~/toc-resume-parser
          docker rm -f resume-app || true
          docker build -t resume-parser-app .
          docker run -d -p 8000:5000 --name resume-app resume-parser-app

