name: Deploy to GCP VM

on:
  push:
    branches:
      - master  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to GCP VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        source: "."
        target: "~/toc-resume-parser"

    - name: Run Docker on GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        script: |
          cd ~/toc-resume-parser
          docker rm -f resume-app || true
          docker build -t toc-resume-parser-app .
          docker run -d -p 80:5000 --name resume-app toc-resume-parser-app
